# Allow replication connections from slave
host    replication     repr_user       10.0.2.0/24             md5
# Allow general connections
host    all             all             0.0.0.0/0               md5