# Allow replication connections from slave
host    replication     repl_user       10.0.2.0/24             md5
# Allow general connections
host    all             all             0.0.0.0/0               md5
# Allow connections from innternal services
local   all             all                                     trust