listen_addresses = '*'
port = 5434
hot_standby = on
max_connections = 100
shared_buffers = 128MB
wal_retrieve_retry_interval = 5s
primary_conninfo = 'host=10.0.2.10 port=5433 user=repl_user password=repl_pass'